In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import GridSearchCV

In [ ]:
df = pd.read_csv(r"C:\Users\lenovo\OneDrive\Desktop\sklearn-models\data\student_performance_dataset.csv")
df.head()

Student_ID  Gender  Study_Hours_per_Week  Attendance_Rate  Past_Exam_Scores  \
0       S147    Male                    31        68.267841                86   
1       S136    Male                    16        78.222927                73   
2       S209  Female                    21        87.525096                74   
3       S458  Female                    27        92.076483                99   
4       S078  Female                    37        98.655517                63   

  Parental_Education_Level Internet_Access_at_Home Extracurricular_Activities  \
0              High School                     Yes                        Yes   
1                      PhD                      No                         No   
2                      PhD                     Yes                         No   
3                Bachelors                      No                         No   
4                  Masters                      No                        Yes   

   Final_Exam_Score Pass_Fail  
0                63      Pass  
1                50      Fail  
2                55      Fail  
3                65      Pass  
4                70      Pass

In [ ]:
df.shape

(708, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Student_ID                  708 non-null    object 
 1   Gender                      708 non-null    object 
 2   Study_Hours_per_Week        708 non-null    int64  
 3   Attendance_Rate             708 non-null    float64
 4   Past_Exam_Scores            708 non-null    int64  
 5   Parental_Education_Level    708 non-null    object 
 6   Internet_Access_at_Home     708 non-null    object 
 7   Extracurricular_Activities  708 non-null    object 
 8   Final_Exam_Score            708 non-null    int64  
 9   Pass_Fail                   708 non-null    object 
dtypes: float64(1), int64(3), object(6)
memory usage: 55.4+ KB


In [ ]:
df.columns.unique()

Index(['Student_ID', 'Gender', 'Study_Hours_per_Week', 'Attendance_Rate',
       'Past_Exam_Scores', 'Parental_Education_Level',
       'Internet_Access_at_Home', 'Extracurricular_Activities',
       'Final_Exam_Score', 'Pass_Fail'],
      dtype='object')

In [ ]:
df = df.drop(columns=['Student_ID', 'Final_Exam_Score'])

In [ ]:
df.columns

Index(['Gender', 'Study_Hours_per_Week', 'Attendance_Rate', 'Past_Exam_Scores',
       'Parental_Education_Level', 'Internet_Access_at_Home',
       'Extracurricular_Activities', 'Pass_Fail'],
      dtype='object')

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

Gender  Study_Hours_per_Week  Attendance_Rate  Past_Exam_Scores  \
0      Male                    31        68.267841                86   
1      Male                    16        78.222927                73   
2    Female                    21        87.525096                74   
3    Female                    27        92.076483                99   
4    Female                    37        98.655517                63   
..      ...                   ...              ...               ...   
701  Female                    21        69.858192                90   
702  Female                    22        93.349688                76   
703    Male                    14        84.658761                78   
705    Male                    25        98.384969                75   
707  Female                    22        80.404392                93   

    Parental_Education_Level Internet_Access_at_Home  \
0                High School                     Yes   
1                        PhD                      No   
2                        PhD                     Yes   
3                  Bachelors                      No   
4                    Masters                      No   
..                       ...                     ...   
701                  Masters                     Yes   
702                Bachelors                      No   
703                      PhD                     Yes   
705                Bachelors                     Yes   
707                Bachelors                     Yes   

    Extracurricular_Activities Pass_Fail  
0                          Yes      Pass  
1                           No      Fail  
2                           No      Fail  
3                           No      Pass  
4                          Yes      Pass  
..                         ...       ...  
701                         No      Fail  
702                         No      Pass  
703                         No      Fail  
705                         No      Fail  
707                         No      Fail  

[500 rows x 8 columns]

In [ ]:
df.shape

(500, 8)

In [ ]:
df['Pass_Fail'].value_counts()

Pass_Fail
Fail    354
Pass    146
Name: count, dtype: int64

In [ ]:
df['Pass_Fail'] = df['Pass_Fail'].map({'Pass': 1, 'Fail':0})

In [ ]:
df['Pass_Fail']

0      1
1      0
2      0
3      1
4      1
      ..
701    0
702    1
703    0
705    0
707    0
Name: Pass_Fail, Length: 500, dtype: int64

In [ ]:
df['Pass_Fail'].isna().sum()

np.int64(0)

In [ ]:
string_col = [
    'Gender',
    'Internet_Access_at_Home'
]

for col in string_col:
    df[col] = df[col].str.strip()

In [ ]:
df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})
df['Gender']

0      1
1      1
2      0
3      0
4      0
      ..
701    0
702    0
703    1
705    1
707    0
Name: Gender, Length: 500, dtype: int64

In [ ]:
df["Internet_Access_at_Home"] = df["Internet_Access_at_Home"].map({"Yes": 1, "No": 0})
df['Internet_Access_at_Home']

0      1
1      0
2      1
3      0
4      0
      ..
701    1
702    0
703    1
705    1
707    1
Name: Internet_Access_at_Home, Length: 500, dtype: int64

In [ ]:
df["Extracurricular_Activities"] = df["Extracurricular_Activities"].map({"Yes": 1, "No": 0})
df['Extracurricular_Activities']

0      1
1      0
2      0
3      0
4      1
      ..
701    0
702    0
703    0
705    0
707    0
Name: Extracurricular_Activities, Length: 500, dtype: int64

In [ ]:
df.isna().sum()

Gender                        0
Study_Hours_per_Week          0
Attendance_Rate               0
Past_Exam_Scores              0
Parental_Education_Level      0
Internet_Access_at_Home       0
Extracurricular_Activities    0
Pass_Fail                     0
dtype: int64

In [ ]:
df["Parental_Education_Level"].unique()

array(['High School', 'PhD', 'Bachelors', 'Masters'], dtype=object)

In [ ]:
eduction_map = {
    'High School' : 0,
    'Bachelors': 1,
    'Masters': 2,
    'PhD':3
}

df['Parental_Education_Level'] = df['Parental_Education_Level'].map(eduction_map)

In [ ]:
df.head()

Gender  Study_Hours_per_Week  Attendance_Rate  Past_Exam_Scores  \
0       1                    31        68.267841                86   
1       1                    16        78.222927                73   
2       0                    21        87.525096                74   
3       0                    27        92.076483                99   
4       0                    37        98.655517                63   

   Parental_Education_Level  Internet_Access_at_Home  \
0                         0                        1   
1                         3                        0   
2                         3                        1   
3                         1                        0   
4                         2                        0   

   Extracurricular_Activities  Pass_Fail  
0                           1          1  
1                           0          0  
2                           0          0  
3                           0          1  
4                           1          1

In [ ]:
df.dtypes

Gender                          int64
Study_Hours_per_Week            int64
Attendance_Rate               float64
Past_Exam_Scores                int64
Parental_Education_Level        int64
Internet_Access_at_Home         int64
Extracurricular_Activities      int64
Pass_Fail                       int64
dtype: object

In [ ]:
X = df.drop('Pass_Fail', axis=1)
y = df['Pass_Fail']

In [ ]:
X

Gender  Study_Hours_per_Week  Attendance_Rate  Past_Exam_Scores  \
0         1                    31        68.267841                86   
1         1                    16        78.222927                73   
2         0                    21        87.525096                74   
3         0                    27        92.076483                99   
4         0                    37        98.655517                63   
..      ...                   ...              ...               ...   
701       0                    21        69.858192                90   
702       0                    22        93.349688                76   
703       1                    14        84.658761                78   
705       1                    25        98.384969                75   
707       0                    22        80.404392                93   

     Parental_Education_Level  Internet_Access_at_Home  \
0                           0                        1   
1                           3                        0   
2                           3                        1   
3                           1                        0   
4                           2                        0   
..                        ...                      ...   
701                         2                        1   
702                         1                        0   
703                         3                        1   
705                         1                        1   
707                         1                        1   

     Extracurricular_Activities  
0                             1  
1                             0  
2                             0  
3                             0  
4                             1  
..                          ...  
701                           0  
702                           0  
703                           0  
705                           0  
707                           0  

[500 rows x 7 columns]

In [ ]:
df

Gender  Study_Hours_per_Week  Attendance_Rate  Past_Exam_Scores  \
0         1                    31        68.267841                86   
1         1                    16        78.222927                73   
2         0                    21        87.525096                74   
3         0                    27        92.076483                99   
4         0                    37        98.655517                63   
..      ...                   ...              ...               ...   
701       0                    21        69.858192                90   
702       0                    22        93.349688                76   
703       1                    14        84.658761                78   
705       1                    25        98.384969                75   
707       0                    22        80.404392                93   

     Parental_Education_Level  Internet_Access_at_Home  \
0                           0                        1   
1                           3                        0   
2                           3                        1   
3                           1                        0   
4                           2                        0   
..                        ...                      ...   
701                         2                        1   
702                         1                        0   
703                         3                        1   
705                         1                        1   
707                         1                        1   

     Extracurricular_Activities  Pass_Fail  
0                             1          1  
1                             0          0  
2                             0          0  
3                             0          1  
4                             1          1  
..                          ...        ...  
701                           0          0  
702                           0          1  
703                           0          0  
705                           0          0  
707                           0          0  

[500 rows x 8 columns]

In [ ]:
df.columns.unique()

Index(['Gender', 'Study_Hours_per_Week', 'Attendance_Rate', 'Past_Exam_Scores',
       'Parental_Education_Level', 'Internet_Access_at_Home',
       'Extracurricular_Activities', 'Pass_Fail'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train.shape, X_test.shape

((400, 7), (100, 7))

In [ ]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

Pass_Fail
0    0.71
1    0.29
Name: proportion, dtype: float64

In [ ]:
num_cols = [
    "Study_Hours_per_Week",
    "Attendance_Rate",
    "Past_Exam_Scores"
]

In [ ]:
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])

In [ ]:
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [ ]:
log_reg = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [ ]:
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
y_pred = log_reg.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0])

In [ ]:
y_prob = log_reg.predict_proba(X_test)[:, 1]
y_prob

array([4.96335293e-02, 4.57258789e-01, 1.58987360e-01, 1.00404027e-02,
       6.64466725e-01, 8.79913993e-02, 5.07770958e-01, 2.45111473e-02,
       1.08901510e-01, 2.04977317e-01, 2.57313395e-02, 6.75800455e-02,
       1.24340402e-01, 5.25333201e-02, 5.35119885e-01, 5.68160593e-01,
       7.01605532e-01, 1.41079845e-01, 3.80360129e-03, 2.28380393e-03,
       6.27123261e-01, 7.40623744e-01, 7.91805434e-04, 3.02734450e-02,
       2.49815907e-01, 1.52813705e-01, 8.44231954e-01, 1.77976607e-01,
       6.18919963e-03, 1.38026659e-01, 6.07754535e-01, 6.04581956e-01,
       1.72404115e-01, 1.35550908e-01, 8.24405265e-03, 7.28252477e-04,
       3.98745806e-03, 9.44832780e-01, 7.89398566e-04, 6.51011823e-02,
       3.41574090e-01, 3.13806960e-01, 3.90839368e-01, 1.06545974e-02,
       2.13971736e-02, 7.15136033e-02, 7.99618317e-01, 5.12259624e-01,
       2.94427067e-03, 1.83795504e-02, 4.99011311e-01, 7.41495798e-01,
       4.82183294e-03, 8.27641738e-01, 6.48731237e-01, 4.48417178e-01,
      

In [ ]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[58, 13],
       [10, 19]])

In [ ]:
accuracy_score(y_test, y_pred)

0.77

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83        71
           1       0.59      0.66      0.62        29

    accuracy                           0.77       100
   macro avg       0.72      0.74      0.73       100
weighted avg       0.78      0.77      0.77       100



In [ ]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [ ]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [ ]:
y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:, 1]

In [ ]:
print("Logistic Regression Confusion Matrix")
cm_lr = confusion_matrix(y_test, y_pred)
print(cm_lr)

print("\nLogistic Regression Classification Report")
print(classification_report(y_test, y_pred))

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))

Logistic Regression Confusion Matrix
[[58 13]
 [10 19]]

Logistic Regression Classification Report
              precision    recall  f1-score   support

           0       0.85      0.82      0.83        71
           1       0.59      0.66      0.62        29

    accuracy                           0.77       100
   macro avg       0.72      0.74      0.73       100
weighted avg       0.78      0.77      0.77       100

Logistic Regression Accuracy: 0.77


In [ ]:
print("Random Forest Confusion Matrix")
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)

print("\nRandom Forest Classification Report")
print(classification_report(y_test, y_pred_rf))

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))


Random Forest Confusion Matrix
[[60 11]
 [14 15]]

Random Forest Classification Report
              precision    recall  f1-score   support

           0       0.81      0.85      0.83        71
           1       0.58      0.52      0.55        29

    accuracy                           0.75       100
   macro avg       0.69      0.68      0.69       100
weighted avg       0.74      0.75      0.75       100

Random Forest Accuracy: 0.75


In [ ]:
param_grid_lr = {
    "C": [0.01, 0.1, 1, 10, 100],
    "penalty": ["l2"],
    "solver": ["liblinear"]
}

param_grid_lr

{'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l2'], 'solver': ['liblinear']}

In [ ]:
grid_lr = GridSearchCV(
    LogisticRegression(max_iter=1000, random_state=42),
    param_grid=param_grid_lr,
    scoring="precision",
    cv=5,
    n_jobs=-1
)

grid_lr.fit(X_train, y_train)

c:\Users\lenovo\OneDrive\Desktop\sklearn-models\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(


GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000, random_state=42),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l2'],
                         'solver': ['liblinear']},
             scoring='precision')

In [ ]:
grid_lr.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}

In [ ]:
best_lr = grid_lr.best_estimator_
best_lr

LogisticRegression(C=0.01, max_iter=1000, penalty='l2', random_state=42,
                   solver='liblinear')

In [ ]:
y_pred_lr_tuned = best_lr.predict(X_test)

print(confusion_matrix(y_test, y_pred_lr_tuned))
print(classification_report(y_test, y_pred_lr_tuned))

[[66  5]
 [20  9]]
              precision    recall  f1-score   support

           0       0.77      0.93      0.84        71
           1       0.64      0.31      0.42        29

    accuracy                           0.75       100
   macro avg       0.71      0.62      0.63       100
weighted avg       0.73      0.75      0.72       100



In [ ]:
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))

Logistic Regression Accuracy: 0.77


In [ ]:
param_grid_rf = {
    "n_estimators": [100, 200],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

In [ ]:
grid_rf = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid=param_grid_rf,
    scoring="precision",
    cv=5,
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200]},
             scoring='precision')

In [ ]:
best_rf = grid_rf.best_estimator_

y_pred_rf_tuned = best_rf.predict(X_test)

print(confusion_matrix(y_test, y_pred_rf_tuned))
print(classification_report(y_test, y_pred_rf_tuned))

[[63  8]
 [17 12]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.83        71
           1       0.60      0.41      0.49        29

    accuracy                           0.75       100
   macro avg       0.69      0.65      0.66       100
weighted avg       0.73      0.75      0.73       100



In [ ]:
y_prob_lr = best_lr.predict_proba(X_test)[:, 1]
y_prob_lr

array([0.23404608, 0.48399091, 0.44117656, 0.2620349 , 0.45911914,
       0.27914859, 0.50751492, 0.22036875, 0.38592182, 0.38843223,
       0.23848907, 0.34252014, 0.28113395, 0.23865046, 0.45981633,
       0.37654721, 0.38281676, 0.40565624, 0.22121506, 0.11184004,
       0.43612222, 0.39699664, 0.1137066 , 0.31760308, 0.36452452,
       0.31228483, 0.5625137 , 0.35933983, 0.2579962 , 0.3915361 ,
       0.44418304, 0.4496799 , 0.28192864, 0.30206976, 0.18058118,
       0.17574844, 0.16930332, 0.58773874, 0.12112398, 0.27057146,
       0.45640181, 0.4184822 , 0.42297206, 0.21943689, 0.20215975,
       0.39029903, 0.57261385, 0.38563396, 0.17505585, 0.16726598,
       0.49182396, 0.43972339, 0.14900786, 0.53870869, 0.53959356,
       0.37161208, 0.41276565, 0.3358725 , 0.35442589, 0.3016053 ,
       0.31987691, 0.27641063, 0.53161036, 0.23828183, 0.35818805,
       0.32322246, 0.13012178, 0.47350065, 0.24564141, 0.42268794,
       0.35114909, 0.29846397, 0.2238855 , 0.44999725, 0.45731

In [ ]:
thresholds = [0.5, 0.6, 0.7, 0.8]

for t in thresholds:
    y_pred_thresh = (y_prob_lr >= t).astype(int)
    
    print(f"\nThreshold = {t}")
    print(confusion_matrix(y_test, y_pred_thresh))
    print(classification_report(y_test, y_pred_thresh))


Threshold = 0.5
[[66  5]
 [20  9]]
              precision    recall  f1-score   support

           0       0.77      0.93      0.84        71
           1       0.64      0.31      0.42        29

    accuracy                           0.75       100
   macro avg       0.71      0.62      0.63       100
weighted avg       0.73      0.75      0.72       100


Threshold = 0.6
[[71  0]
 [26  3]]
              precision    recall  f1-score   support

           0       0.73      1.00      0.85        71
           1       1.00      0.10      0.19        29

    accuracy                           0.74       100
   macro avg       0.87      0.55      0.52       100
weighted avg       0.81      0.74      0.65       100


Threshold = 0.7
[[71  0]
 [29  0]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83        71
           1       0.00      0.00      0.00        29

    accuracy                           0.71       100
   macro avg       0

c:\Users\lenovo\OneDrive\Desktop\sklearn-models\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\lenovo\OneDrive\Desktop\sklearn-models\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\lenovo\OneDrive\Desktop\sklearn-models\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(averag